package com.altimetrik.trainschedule.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
public class Schedule {

    @Id

    private String  scheduleId;

    @NotNull(message = "Departure DateTime cannot be null")
    private LocalDateTime departureDateTime;

    @NotNull(message = "Arrival DateTime cannot be null")
    private LocalDateTime arrivalDateTime;

    private String  trainId;
    private String routeId;

    // Add getters and setters if not generated by Lombok
}